services:
  - type: web
    name: neuromed-api
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan optimize
    startCommand: |
      php artisan migrate --force
      php -d variables_order=EGPCS -S 0.0.0.0:10000 -t public
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:WLhaXm6pr89i9LgOKz5bnxqwgI1Gv4MeUGNRlggpVkU=
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: sql.freedb.tech
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: freedb_neuromed_db
      - key: DB_USERNAME
        value: freedb_neuromed
      - key: DB_PASSWORD
        value: "%8WczeHD7@UNyhp"